class HouseLordSittingRule:
    def __init__(self):
        # 12x12 prediction matrix based on provided detailed table
        self.prediction_matrix = {
            "1st": {
                "1st": {"code": "1ST_LORD_1ST", "text": "A very powerful placement. Indicates a strong sense of self, independence, good health, and vitality. Success comes through personal effort and charisma. The native is self-reliant and a natural leader.", "confidence": 0.80},
                "2nd": {"code": "1ST_LORD_2ND", "text": "Life focus is on accumulating wealth and supporting the family. The native's identity is tied to their financial status and family values. They are often eloquent speakers and can gain wealth through their own efforts.", "confidence": 0.74},
                "3rd": {"code": "1ST_LORD_3RD", "text": "A self-made individual who succeeds through courage, communication, and personal enterprise. Often skilled with their hands, in writing, or the performing arts. Good relationships with siblings are a source of strength.", "confidence": 0.72},
                "4th": {"code": "1ST_LORD_4TH", "text": "Strong focus on domestic life, mother, and emotional security. Gains happiness and contentment from home, property, and vehicles. Often well-educated and has a strong connection to their roots.", "confidence": 0.74},
                "5th": {"code": "1ST_LORD_5TH", "text": "Highly intelligent, creative, and drawn to intellectual pursuits. Good with children, investments, and speculation. May find success in politics, teaching, or creative fields.", "confidence": 0.76},
                "6th": {"code": "1ST_LORD_6TH", "text": "Life may involve overcoming conflicts, debts, or health issues. While challenging, this placement gives the strength to defeat enemies. Success often comes through service-oriented professions like law or medicine.", "confidence": 0.65},
                "7th": {"code": "1ST_LORD_7TH", "text": "Focus is on partnerships, marriage, and public image. The partner is central to the native's life path. Success in business and a strong social standing are common. May settle or travel abroad.", "confidence": 0.74},
                "8th": {"code": "1ST_LORD_8TH", "text": "A life of transformation, with a deep interest in research, psychology, or the occult. May face sudden ups and downs or chronic health issues, but can also gain from inheritance or unearned wealth. Possesses great longevity.", "confidence": 0.68},
                "9th": {"code": "1ST_LORD_9TH", "text": "A fortunate, wise, and philosophical individual. Deeply connected to their father, guru, or religion. Success comes from higher education, long-distance travel, and righteous conduct.", "confidence": 0.78},
                "10th": {"code": "1ST_LORD_10TH", "text": "Extremely career-focused and ambitious. A natural leader who achieves high status and public recognition. Success is driven by personal ambition and a desire for achievement.", "confidence": 0.82},
                "11th": {"code": "1ST_LORD_11TH", "text": "Excellent for gains and fulfillment of desires. The native has a wide social network of influential friends and receives support from their elder siblings. Success comes easily through social connections.", "confidence": 0.76},
                "12th": {"code": "1ST_LORD_12TH", "text": "A spiritual, introverted, or philosophical nature. May feel isolated or drawn to foreign lands, ashrams, or hospitals. Prone to expenses and losses, but can achieve spiritual liberation (moksha).", "confidence": 0.68}
            },
            "2nd": {
                "1st": {"code": "2ND_LORD_1ST", "text": "Wealth and family are central to the native's identity. They are often born into a good family, are powerful speakers, and attract financial opportunities through their personality.", "confidence": 0.74},
                "2nd": {"code": "2ND_LORD_2ND", "text": "A very powerful placement for wealth (Dhana Yoga). The native is excellent at managing finances, accumulates assets, and has a stable, supportive family life. They are often respected for their speech.", "confidence": 0.80},
                "3rd": {"code": "2ND_LORD_3RD", "text": "Wealth is generated through personal courage, siblings, communication, or artistic pursuits. A good financial manager who succeeds through their own efforts and initiative.", "confidence": 0.72},
                "4th": {"code": "2ND_LORD_4TH", "text": "Gains wealth through mother, real estate, vehicles, or agriculture. Family life is happy and comfortable, and there is a possibility of inheriting property.", "confidence": 0.74},
                "5th": {"code": "2ND_LORD_5TH", "text": "Wealth is generated through intelligence, creativity, speculation, or children. A good placement for success in investments, entertainment, or teaching. The native is learned and eloquent.", "confidence": 0.76},
                "6th": {"code": "2ND_LORD_6TH", "text": "Financial life can be challenging, with potential for debts, disputes, or losses due to health issues. However, can also indicate earnings through service professions like law or medicine, or even through dubious means.", "confidence": 0.65},
                "7th": {"code": "2ND_LORD_7TH", "text": "Wealth comes through the spouse, business partnerships, or foreign trade. The partner may come from a wealthy family, or the native becomes prosperous after marriage.", "confidence": 0.74},
                "8th": {"code": "2ND_LORD_8TH", "text": "Indicates unearned wealth through inheritance, insurance, or lotteries. However, it can also signify sudden financial losses or trouble with family finances. Speech may be harsh or secretive.", "confidence": 0.68},
                "9th": {"code": "2ND_LORD_9TH", "text": "A very fortunate placement for wealth. Gains come from father, higher learning, foreign connections, or religious institutions. The native is lucky and prosperous.", "confidence": 0.78},
                "10th": {"code": "2ND_LORD_10TH", "text": "Wealth is generated directly through a powerful career and public status. Excellent for professional success, especially in finance, management, or government roles.", "confidence": 0.76},
                "11th": {"code": "2ND_LORD_11TH", "text": "A powerful combination for immense wealth (Dhana Yoga). The native gains from all ventures, has a strong network of influential friends, and easily fulfills their desires.", "confidence": 0.80},
                "12th": {"code": "2ND_LORD_12TH", "text": "Indicates financial losses, heavy expenses, and difficulty accumulating wealth. May have speech problems or a difficult family life. Can also indicate earning from foreign lands or spiritual institutions.", "confidence": 0.65}
            },
            "3rd": {
                "1st": {"code": "3RD_LORD_1ST", "text": "A self-made individual whose achievements come from their own hard work. They are courageous, argumentative, and may have strained relations with relatives but possess strong willpower.", "confidence": 0.74},
                "2nd": {"code": "3RD_LORD_2ND", "text": "Gains wealth through personal efforts, communication skills, or with the help of siblings. They are bold in financial matters and have a practical, ambitious mindset.", "confidence": 0.72},
                "3rd": {"code": "3RD_LORD_3RD", "text": "Extremely courageous, determined, and successful in ventures that require risk-taking. A powerful placement for writers, artists, athletes, and entrepreneurs. Has good relationships with siblings.", "confidence": 0.78},
                "4th": {"code": "3RD_LORD_4TH", "text": "Energy is focused on home and family. May build their own house through personal effort. Can indicate a career in real estate or politics. The mother may be a powerful figure.", "confidence": 0.72},
                "5th": {"code": "3RD_LORD_5TH", "text": "A highly creative and intelligent individual. Success in creative arts, writing, sports, or performance. Their children may be very courageous and talented. A good financial speculator.", "confidence": 0.74},
                "6th": {"code": "3RD_LORD_6TH", "text": "A fighter who is courageous in facing enemies and competition. However, this can lead to conflicts with siblings or health issues related to arms and ears. Success in military, law, or service.", "confidence": 0.65},
                "7th": {"code": "3RD_LORD_7TH", "text": "The partner may be entrepreneurial, courageous, or from the neighborhood. Success in business partnerships that require travel and communication. The native is assertive in relationships.", "confidence": 0.72},
                "8th": {"code": "3RD_LORD_8TH", "text": "Can indicate a lack of courage or communication issues. May face sudden, unexpected challenges or have a difficult relationship with siblings. Longevity can be impacted if afflicted.", "confidence": 0.65},
                "9th": {"code": "3RD_LORD_9TH", "text": "Fortune is activated through courageous action, travel, and communication. A righteous person who gains from siblings and higher learning. The father may be a self-made individual.", "confidence": 0.74},
                "10th": {"code": "3RD_LORD_10TH", "text": "Career success is achieved through daring efforts, communication skills, and entrepreneurship. A natural leader in fields like media, marketing, or technology.", "confidence": 0.76},
                "11th": {"code": "3RD_LORD_11TH", "text": "Fulfills desires and achieves great gains through personal enterprise, courage, and a strong social network. Siblings are a source of profit and support.", "confidence": 0.75},
                "12th": {"code": "3RD_LORD_12TH", "text": "May lack initiative or face losses in ventures. Expenses may arise due to siblings. Can indicate working in isolation or in foreign lands. Spiritual strength is gained in solitude.", "confidence": 0.65}
            },
            "4th": {
                "1st": {"code": "4TH_LORD_1ST", "text": "The native is deeply connected to their mother, home, and roots. They are generally happy, well-educated, and may gain land and property. Their identity is shaped by their upbringing.", "confidence": 0.74},
                "2nd": {"code": "4TH_LORD_2ND", "text": "Wealth is gained through property, vehicles, or the mother. The native invests in their home and family, leading a comfortable life. They have a good education and a pleasant speaking voice.", "confidence": 0.74},
                "3rd": {"code": "4TH_LORD_3RD", "text": "Happiness comes from siblings, hobbies, and short travels. May build or acquire property through their own efforts. The mother may be an enterprising figure.", "confidence": 0.72},
                "4th": {"code": "4TH_LORD_4TH", "text": "An excellent placement for domestic happiness (Swa-kshetra). The native is content, owns property and vehicles, and has a strong, positive relationship with their mother. A very stable and fortunate position.", "confidence": 0.78},
                "5th": {"code": "4TH_LORD_5TH", "text": "A very happy and fortunate individual. Gains come from children, creative pursuits, and education. They are intelligent, emotionally content, and may have a successful career in teaching or politics.", "confidence": 0.76},
                "6th": {"code": "4TH_LORD_6TH", "text": "Domestic life can be filled with conflict, debt, or health issues. May face disputes over property or have a difficult relationship with their mother. Can indicate success in service-related fields away from home.", "confidence": 0.65},
                "7th": {"code": "4TH_LORD_7TH", "text": "Gains property and happiness through marriage or business partnerships. The spouse may be focused on domestic life, and the marriage is generally happy and stable.", "confidence": 0.74},
                "8th": {"code": "4TH_LORD_8TH", "text": "Can indicate disturbances in domestic life, loss of property, or issues with the mother's health. However, it can also signify inheritance of property or gains from hidden sources.", "confidence": 0.68},
                "9th": {"code": "4TH_LORD_9TH", "text": "A very fortunate placement. The native is happy, wise, and owns good property and vehicles. Gains from father and higher education. A righteous and philosophical disposition.", "confidence": 0.76},
                "10th": {"code": "4TH_LORD_10TH", "text": "Career is often related to the public, real estate, vehicles, or agriculture. The native enjoys power, status, and comfort derived from their profession.", "confidence": 0.75},
                "11th": {"code": "4TH_LORD_11TH", "text": "Gains property, vehicles, and happiness through friends and social networks. All desires related to home and comfort are fulfilled. A very prosperous and happy life.", "confidence": 0.76},
                "12th": {"code": "4TH_LORD_12TH", "text": "Indicates loss of property or happiness. The native may live far from their homeland or feel emotionally detached. Relationship with the mother can be distant or troubled.", "confidence": 0.65}
            },
            "5th": {
                "1st": {"code": "5TH_LORD_1ST", "text": "A highly intelligent, creative, and charismatic individual. They are natural leaders, good with children, and may be drawn to politics or the performing arts. Their identity is defined by their intellect.", "confidence": 0.76},
                "2nd": {"code": "5TH_LORD_2ND", "text": "Gains wealth through intelligence, creative talents, or speculation. An eloquent speaker and knowledgeable person. Their family life is prosperous, and their children may be wealthy.", "confidence": 0.74},
                "3rd": {"code": "5TH_LORD_3RD", "text": "Success and fame come through creative writing, arts, sports, or media. They have courageous and intelligent children. A strong placement for authors and performers.", "confidence": 0.74},
                "4th": {"code": "5TH_LORD_4TH", "text": "A very happy and emotionally content person. Gains from property, vehicles, and a good education. Their mother is fortunate, and they have a peaceful domestic life centered around children and creativity.", "confidence": 0.75},
                "5th": {"code": "5TH_LORD_5TH", "text": "An extremely powerful placement (Swa-kshetra). The native is highly intelligent, creative, and respected. They have fortunate and talented children and may be a successful advisor, teacher, or entertainer.", "confidence": 0.80},
                "6th": {"code": "5TH_LORD_6TH", "text": "Can indicate challenges related to children (health issues, debts) or breaks in education. However, it also gives success in competitive fields like sports or competitive exams. May adopt a child.", "confidence": 0.65},
                "7th": {"code": "5TH_LORD_7TH", "text": "Indicates a love marriage or a very romantic partnership. The spouse is intelligent, creative, and may be famous. Success in business partnerships, especially in creative or entertainment fields.", "confidence": 0.76},
                "8th": {"code": "5TH_LORD_8TH", "text": "Can cause breaks in education or issues with children. However, it can also bring sudden, unexpected gains through speculation, lotteries, or insurance. A deep interest in research and mysteries.", "confidence": 0.68},
                "9th": {"code": "5TH_LORD_9TH", "text": "A highly fortunate (Raja Yoga) and wise individual. They follow a righteous path and are blessed with good children and a fortunate father. Success as a teacher, advisor, or spiritual leader.", "confidence": 0.78},
                "10th": {"code": "5TH_LORD_10TH", "text": "A powerful career in government, entertainment, politics, or management. The native is a respected public figure whose intelligence and creativity bring them fame and authority.", "confidence": 0.79},
                "11th": {"code": "5TH_LORD_11TH", "text": "A fantastic placement for gains. Wealth and fulfillment of desires come through creative ventures, children, and investments. They have a network of powerful and creative friends.", "confidence": 0.77},
                "12th": {"code": "5TH_LORD_12TH", "text": "May indicate losses in speculation or challenges related to children. Can lead to foreign travel for education. The native may have a strong spiritual inclination and express their creativity in isolation or through spiritual arts.", "confidence": 0.65}
            },
            "6th": {
                "1st": {"code": "6TH_LORD_1ST", "text": "The native may face health issues or be troubled by enemies, but they are also a fighter who is bold and courageous. Can indicate a career in uniformed services or law. May cause trouble for their own family.", "confidence": 0.65},
                "2nd": {"code": "6TH_LORD_2ND", "text": "Financial problems due to debts, enemies, or health expenses. May have conflicts with family over money. Can also indicate earning wealth through service, law, or medicine.", "confidence": 0.65},
                "3rd": {"code": "6TH_LORD_3RD", "text": "Conflicts with siblings or neighbors. Courageous in facing competition and enemies. May have health issues related to arms or the nervous system. A good placement for success in competitive sports or media.", "confidence": 0.65},
                "4th": {"code": "6TH_LORD_4TH", "text": "Domestic life is disturbed by conflicts, legal issues over property, or ill health of the mother. The native may feel a lack of peace at home. Can indicate a career in service related to real estate.", "confidence": 0.65},
                "5th": {"code": "6TH_LORD_5TH", "text": "Challenges related to children, who may be sickly or behave like enemies. May face obstacles in education or creative pursuits. Success in competitive exams is possible.", "confidence": 0.65},
                "6th": {"code": "6TH_LORD_6TH", "text": "Creates a powerful Viparita Raja Yoga. The native is extremely strong, defeats all enemies, overcomes debts and diseases, and achieves great success through service. A very powerful placement for lawyers, doctors, or politicians.", "confidence": 0.75},
                "7th": {"code": "6TH_LORD_7TH", "text": "Indicates conflicts and disputes in marriage or business partnerships. The partner may be argumentative or have chronic health issues. Success in legal partnerships is possible.", "confidence": 0.65},
                "8th": {"code": "6TH_LORD_8TH", "text": "Another powerful Viparita Raja Yoga. The native overcomes chronic diseases and powerful hidden enemies to achieve unexpected success and wealth. Can indicate a long life after initial struggles.", "confidence": 0.72},
                "9th": {"code": "6TH_LORD_9TH", "text": "Conflicts with father, teachers, or guru. Obstacles in higher education and foreign travel. Fortune and luck only come after significant struggle and overcoming obstacles.", "confidence": 0.65},
                "10th": {"code": "6TH_LORD_10TH", "text": "Career is often in service-related fields (medicine, law, social work). The native faces many obstacles and enemies in their professional life but can rise to a high position by overcoming them.", "confidence": 0.72},
                "11th": {"code": "6TH_LORD_11TH", "text": "Gains and income are blocked or come only after great struggle. Friends may turn into enemies, or the native may have conflicts within their social network. Elder sibling may face difficulties.", "confidence": 0.65},
                "12th": {"code": "6TH_LORD_12TH", "text": "A third powerful Viparita Raja Yoga. The native overcomes hidden enemies and losses. Expenses are often related to health or legal issues. Can indicate work in hospitals, prisons, or foreign lands, leading to spiritual growth.", "confidence": 0.70}
            },
            "7th": {
                "1st": {"code": "7TH_LORD_1ST", "text": "The partner has a very strong influence on the native's life and identity. Often indicates that the native's status rises after marriage. The partner may be a dominant personality.", "confidence": 0.76},
                "2nd": {"code": "7TH_LORD_2ND", "text": "Financial gains through the spouse or business partnerships. The partner may be from a wealthy family, and the marriage brings prosperity and stability to the native's family life.", "confidence": 0.74},
                "3rd": {"code": "7TH_LORD_3RD", "text": "The relationship is built on communication and shared intellectual interests. The partner may be an entrepreneur or involved in media/writing. Success in business partnerships requiring courage and travel.", "confidence": 0.72},
                "4th": {"code": "7TH_LORD_4TH", "text": "A very happy domestic life. The partner is focused on home and family, and the marriage brings emotional security and comfort. May gain property through the spouse.", "confidence": 0.75},
                "5th": {"code": "7TH_LORD_5TH", "text": "A strong indication of a love marriage. The partner is romantic, creative, and intelligent. Success in business partnerships related to entertainment, education, or speculation.", "confidence": 0.76},
                "6th": {"code": "7TH_LORD_6TH", "text": "Marriage and partnerships can be filled with conflict, disputes, or health issues. The spouse may work in a service field (law, medicine). The native must work hard to maintain harmony.", "confidence": 0.65},
                "7th": {"code": "7TH_LORD_7TH", "text": "An excellent placement (Swa-kshetra). The native has a strong, trustworthy, and supportive partner. Marriage is stable and balanced, and there is great success in business and public life.", "confidence": 0.80},
                "8th": {"code": "7TH_LORD_8TH", "text": "Can indicate turmoil, secrets, or sudden transformations in marriage. The partner may be involved in research or occult fields. Can also bring wealth from the partner's family (inheritance).", "confidence": 0.68},
                "9th": {"code": "7TH_LORD_9TH", "text": "A very fortunate marriage. The partner is wise, righteous, and may be from a different culture or met during travel. The marriage brings luck and spiritual growth.", "confidence": 0.78},
                "10th": {"code": "7TH_LORD_10TH", "text": "The partner is career-oriented, ambitious, and may have a high public status. The native's own career and reputation are strongly influenced by their marriage and partnerships.", "confidence": 0.77},
                "11th": {"code": "7TH_LORD_11TH", "text": "Gains and fulfillment of desires come through marriage and partnerships. The spouse may be from one's social circle and helps expand the native's network and income.", "confidence": 0.76},
                "12th": {"code": "7TH_LORD_12TH", "text": "The spouse may be from a foreign land, or the native may settle abroad after marriage. Can indicate separation or a relationship that is very private and spiritual in nature. Potential for losses in business partnerships.", "confidence": 0.65}
            },
            "8th": {
                "1st": {"code": "8TH_LORD_1ST", "text": "A life marked by transformation and potential health challenges. The native is a natural researcher, deeply intuitive, and may have a strong interest in the occult. Can indicate a long life if well-placed.", "confidence": 0.70},
                "2nd": {"code": "8TH_LORD_2ND", "text": "Financial life is subject to sudden ups and downs. Can bring great wealth through inheritance or insurance, but also sudden losses. May have issues with family wealth or harsh speech.", "confidence": 0.68},
                "3rd": {"code": "8TH_LORD_3RD", "text": "Can indicate a difficult relationship with siblings or loss of courage. The native may face sudden and unexpected challenges in their endeavors. Communication can be secretive or profound.", "confidence": 0.65},
                "4th": {"code": "8TH_LORD_4TH", "text": "Disturbances in domestic life, sudden changes of residence, or issues with the mother's health. Can also indicate inheritance of property or discovering hidden things at home.", "confidence": 0.68},
                "5th": {"code": "8TH_LORD_5TH", "text": "Potential for sudden gains through speculation or lotteries. However, can also indicate challenges with children or breaks in education. A deep, research-oriented intellect.", "confidence": 0.68},
                "6th": {"code": "8TH_LORD_6TH", "text": "A powerful Viparita Raja Yoga. The native overcomes powerful enemies and chronic diseases through sudden, unexpected events, leading to great success and status.", "confidence": 0.72},
                "7th": {"code": "8TH_LORD_7TH", "text": "Marriage and partnerships may undergo dramatic transformations, or there could be secrets within the relationship. The partner may be involved in research, healing, or managing joint finances.", "confidence": 0.68},
                "8th": {"code": "8TH_LORD_8TH", "text": "An excellent placement for longevity (Swa-kshetra). The native is a master of research, deeply intuitive, and may gain significant wealth through inheritance or their partner. A powerful, transformative personality.", "confidence": 0.75},
                "9th": {"code": "8TH_LORD_9TH", "text": "Can indicate challenges for the father or obstacles in higher education and fortune. The native may have a deep interest in hidden spiritual knowledge and philosophy, finding luck in unconventional ways.", "confidence": 0.68},
                "10th": {"code": "8TH_LORD_10TH", "text": "Career is often in fields that involve secrets, research, or transformation, such as detective work, insurance, mining, or psychology. The professional life is marked by sudden ups and downs.", "confidence": 0.70},
                "11th": {"code": "8TH_LORD_11TH", "text": "Gains from unexpected or hidden sources like insurance, inheritance, or lotteries. However, friendships can be secretive, and income can be subject to sudden fluctuations.", "confidence": 0.68},
                "12th": {"code": "8TH_LORD_12TH", "text": "Another powerful Viparita Raja Yoga. The native achieves spiritual liberation or success in foreign lands after overcoming hidden obstacles and losses. A deep interest in meditation and the subconscious mind.", "confidence": 0.72}
            },
            "9th": {
                "1st": {"code": "9TH_LORD_1ST", "text": "A very fortunate, wise, and respected individual. They are righteous, philosophical, and have a good relationship with their father. Their personality radiates wisdom and luck.", "confidence": 0.78},
                "2nd": {"code": "9TH_LORD_2ND", "text": "Gains wealth through good fortune, father, higher education, or foreign connections. The native comes from a respected family and is a wise and truthful speaker.", "confidence": 0.76},
                "3rd": {"code": "9TH_LORD_3RD", "text": "Fortune is activated through courage, writing, and communication. Siblings are fortunate and supportive. Success in teaching, publishing, or as a consultant. A wise and enterprising individual.", "confidence": 0.74},
                "4th": {"code": "9TH_LORD_4TH", "text": "Blessed with happiness, good education, property, and vehicles. The mother is righteous, and the father is supportive of the domestic environment. A very fortunate and comfortable home life.", "confidence": 0.76},
                "5th": {"code": "9TH_LORD_5TH", "text": "A powerful Raja Yoga, indicating a highly intelligent, fortunate, and creative person. Blessed with wise and talented children. Success as a high-level advisor, minister, or teacher.", "confidence": 0.80},
                "6th": {"code": "9TH_LORD_6TH", "text": "Fortune comes only after overcoming conflicts and obstacles. May have disagreements with father or teachers. Success in law or service in foreign lands is possible through righteousness.", "confidence": 0.65},
                "7th": {"code": "9TH_LORD_7TH", "text": "A very fortunate marriage to a wise, righteous, and respected partner. The partner may be from a different culture. Gains and luck come through partnerships and foreign travel.", "confidence": 0.78},
                "8th": {"code": "9TH_LORD_8TH", "text": "Can indicate challenges for the father or breaks in fortune. However, it also signifies inheritance and a deep interest in spiritual and occult wisdom. Luck may come from unexpected sources.", "confidence": 0.68},
                "9th": {"code": "9TH_LORD_9TH", "text": "An extremely fortunate placement (Swa-kshetra). The native is a wise, philosophical, and respected leader. They have an excellent relationship with their father and are blessed with good fortune in all endeavors.", "confidence": 0.82},
                "10th": {"code": "9TH_LORD_10TH", "text": "A powerful Raja Yoga for a highly successful and respected career. The native becomes a leader, teacher, judge, or works in a high-status position in government or a large corporation. Their career is guided by righteousness.", "confidence": 0.80},
                "11th": {"code": "9TH_LORD_11TH", "text": "A fantastic placement for wealth and fulfillment of desires. The native is extremely fortunate, gaining from their father, friends, and all professional ventures. A very wealthy and influential person.", "confidence": 0.79},
                "12th": {"code": "9TH_LORD_12TH", "text": "Fortune is often found in foreign lands or through spiritual pursuits. May have expenses related to education, travel, or charity. The relationship with the father may be distant.", "confidence": 0.68}
            },
            "10th": {
                "1st": {"code": "10TH_LORD_1ST", "text": "A self-made person who is highly focused on their career. Their work is central to their identity. A natural entrepreneur and leader who achieves success through their own ambition and persistence.", "confidence": 0.82},
                "2nd": {"code": "10TH_LORD_2ND", "text": "Earns wealth through their profession and achieves a high status. Often follows the family profession or works in finance, management, or as a public speaker. A very prosperous career.", "confidence": 0.76},
                "3rd": {"code": "10TH_LORD_3RD", "text": "Career involves communication, marketing, media, writing, or entrepreneurship. Success is achieved through courage, personal skills, and taking initiative. May work with siblings.", "confidence": 0.74},
                "4th": {"code": "10TH_LORD_4TH", "text": "Career is often related to real estate, vehicles, agriculture, or public service. The native enjoys comfort and influence derived from their profession and may work from home.", "confidence": 0.75},
                "5th": {"code": "10TH_LORD_5TH", "text": "A career in creative fields, entertainment, politics, teaching, or speculation. The native's intelligence and creativity bring them public recognition and authority.", "confidence": 0.78},
                "6th": {"code": "10TH_LORD_6TH", "text": "Career is often in service-oriented fields like law, medicine, or security. The native faces many obstacles and enemies in their work but can rise to a high position by overcoming them.", "confidence": 0.72},
                "7th": {"code": "10TH_LORD_7TH", "text": "Success comes through business partnerships, diplomacy, or public relations. The spouse is often a key figure in the native's career. The work involves dealing with the public.", "confidence": 0.76},
                "8th": {"code": "10TH_LORD_8TH", "text": "Career is marked by sudden changes and may be in fields involving research, secrets, or transformation, such as insurance, mining, detective work, or psychology. Many breaks in career are possible.", "confidence": 0.68},
                "9th": {"code": "10TH_LORD_9TH", "text": "A fortunate and respected career. The native may be a professor, judge, consultant, or religious leader. Career often involves higher learning and long-distance travel, possibly to foreign lands.", "confidence": 0.80},
                "10th": {"code": "10TH_LORD_10TH", "text": "An extremely powerful placement (Swa-kshetra). The native is a renowned leader with high status, authority, and great professional achievements. Their career is stable and successful.", "confidence": 0.84},
                "11th": {"code": "10TH_LORD_11TH", "text": "Great gains and success through career. The native achieves their professional ambitions and has a network of powerful friends who support their work. A very profitable and fulfilling career.", "confidence": 0.80},
                "12th": {"code": "10TH_LORD_12TH", "text": "Career often involves foreign lands, hospitals, prisons, spiritual institutions, or work done in isolation. May face setbacks or work behind the scenes. Can indicate success in import-export business.", "confidence": 0.68}
            },
            "11th": {
                "1st": {"code": "11TH_LORD_1ST", "text": "A very fortunate placement. The native is well-liked, has a strong social network, and achieves their goals through their own personality and efforts. They are naturally successful and attract opportunities.", "confidence": 0.78},
                "2nd": {"code": "11TH_LORD_2ND", "text": "A powerful Dhana Yoga for wealth. Gains come through family, speech, and savings. The native is prosperous, has a resourceful family, and may earn from banking or food-related businesses.", "confidence": 0.80},
                "3rd": {"code": "11TH_LORD_3RD", "text": "Gains are achieved through courage, self-effort, communication, and siblings. Success in media, writing, or personal business ventures. A very enterprising individual.", "confidence": 0.74},
                "4th": {"code": "11TH_LORD_4TH", "text": "Gains come from property, vehicles, mother, and homeland. A comfortable and happy life with all desires for domestic peace fulfilled. Success in real estate or agriculture.", "confidence": 0.76},
                "5th": {"code": "11TH_LORD_5TH", "text": "A powerful Dhana Yoga. Gains come from creativity, intelligence, children, and speculation. The native is popular and successful in fields like entertainment, teaching, or investing.", "confidence": 0.78},
                "6th": {"code": "11TH_LORD_6TH", "text": "Income comes through service, legal matters, or medicine. The native gains by defeating enemies and overcoming obstacles. However, it can also indicate gains through illicit means.", "confidence": 0.68},
                "7th": {"code": "11TH_LORD_7TH", "text": "Gains come through marriage, business partnerships, and public relations. The spouse is often wealthy and influential, and the native prospers after marriage.", "confidence": 0.76},
                "8th": {"code": "11TH_LORD_8TH", "text": "Gains from unearned sources like inheritance, insurance, or lotteries. Can also indicate profits from research or occult sciences. However, income can be subject to sudden fluctuations.", "confidence": 0.68},
                "9th": {"code": "11TH_LORD_9TH", "text": "A highly fortunate placement (Raja Yoga). The native is extremely wealthy, with gains coming from father, guru, higher education, and foreign travel. All desires are fulfilled.", "confidence": 0.80},
                "10th": {"code": "11TH_LORD_10TH", "text": "Gains come directly from a powerful career and high status. The native is successful, respected, and achieves all professional ambitions. A strong placement for leadership and wealth.", "confidence": 0.79},
                "11th": {"code": "11TH_LORD_11TH", "text": "The ultimate placement for gains (Swa-kshetra). The native is extremely wealthy, influential, and has a powerful network of friends. All desires are easily fulfilled, and they achieve great success in all undertakings.", "confidence": 0.84},
                "12th": {"code": "11TH_LORD_12TH", "text": "Income often comes from foreign sources, import-export business, or institutions like hospitals and ashrams. However, it can also indicate high expenses and losses. Friends may cause financial drain.", "confidence": 0.68}
            },
            "12th": {
                "1st": {"code": "12TH_LORD_1ST", "text": "The native may be physically weak, prone to illness, and face many obstacles. They are often spendthrifts and may have a spiritual or philosophical inclination. Can indicate settlement in foreign lands.", "confidence": 0.68},
                "2nd": {"code": "12TH_LORD_2ND", "text": "Indicates financial losses and heavy expenses, especially related to family. The native struggles to accumulate wealth. Can also indicate earning from foreign sources. May have speech issues.", "confidence": 0.65},
                "3rd": {"code": "12TH_LORD_3RD", "text": "Lack of courage and initiative. Difficult relationships with siblings, who may cause expenses or live far away. Communication can be a source of loss or misunderstanding.", "confidence": 0.65},
                "4th": {"code": "12TH_LORD_4TH", "text": "Loss of domestic happiness or property. The native may live far from their birthplace. The relationship with the mother can be distant or troubled. Can cause mental unrest and sleep disorders.", "confidence": 0.65},
                "5th": {"code": "12TH_LORD_5TH", "text": "Challenges related to children, such as high expenses, separation, or health issues. Losses in speculation and investments. Can indicate breaks in higher education. May lead to spiritual pursuits due to life's disappointments.", "confidence": 0.65},
                "6th": {"code": "12TH_LORD_6TH", "text": "A powerful Viparita Raja Yoga. The native overcomes hidden enemies, debts, and diseases to achieve unexpected success. They turn loss into gain. A good placement for success in healing or service professions.", "confidence": 0.72},
                "7th": {"code": "12TH_LORD_7TH", "text": "Can indicate separation, divorce, or a partner from a foreign land. Losses in business partnerships. The relationship may be very private or have a spiritual dimension.", "confidence": 0.65},
                "8th": {"code": "12TH_LORD_8TH", "text": "Another powerful Viparita Raja Yoga. The native gains from hidden sources and has a long life. A deep interest in spirituality, research, and the occult. They find wisdom through transformative experiences.", "confidence": 0.72},
                "9th": {"code": "12TH_LORD_9TH", "text": "Indicates expenses on foreign travel, higher education, or religious pursuits. The relationship with the father may be distant or there could be a loss of fortune. Can also indicate a spiritual path involving foreign cultures.", "confidence": 0.68},
                "10th": {"code": "12TH_LORD_10TH", "text": "Career is often in foreign lands or in isolated institutions like hospitals, ashrams, or prisons. May face setbacks, instability, or work behind the scenes. Can also indicate a spiritual career.", "confidence": 0.65},
                "11th": {"code": "12TH_LORD_11TH", "text": "Gains and income are subject to losses and high expenses. Friendships may be a source of financial drain. Desires may be hard to fulfill, leading to frustration.", "confidence": 0.65},
                "12th": {"code": "12TH_LORD_12TH", "text": "A powerful Viparita Raja Yoga (Swa-kshetra). The native is highly spiritual, detached, and may achieve enlightenment (moksha). They spend money on good causes and may live permanently in a foreign land. Excellent for spiritual progress.", "confidence": 0.75}
            }
        }

    def evaluate(self, profile_id, planets_data):
        """Evaluate house lord placements for predictions."""
        import logging
        logger = logging.getLogger(__name__)
        try:
            predictions = []
            # Iterate through planets to check lordship and placement
            for planet in planets_data:
                house_lordship = planet.get("house_lordship", "")
                if not house_lordship:
                    continue
                placement_house = str(planet.get("house")) + "th"
                # Check each house the planet rules
                for lorded_house in house_lordship.split(","):
                    if lorded_house in self.prediction_matrix:
                        prediction = self.prediction_matrix[lorded_house].get(placement_house)
                        if prediction:
                            predictions.append({
                                "prediction_code": prediction["code"],
                                "text": prediction["text"],
                                "confidence": prediction["confidence"],
                                "source_rule": "HOUSE_LORD_SITTING",
                                "profile_id": profile_id
                            })
                            logger.debug(f"Generated prediction: {prediction['code']} for {lorded_house} lord in {placement_house}")
            logger.info(f"Generated {len(predictions)} house lord predictions for profile {profile_id}")
            return predictions
        except Exception as e:
            logger.error(f"Error evaluating house lord rule: {e}")
            raise